issue/64 Add aria-current='true' to button for screen readers
adaptlearning/adapt-contrib-languagePicker pull request #65
Opened 2022-05-12 14:07 UTC by StuartNicholls

fixes #64

2022-05-12 14:20 UTC, oliverfoster approved these changes

2022-05-23 11:44 UTC, StuartNicholls commented on templates/languagePickerDrawerView.hbs
> +        <button class="languagepicker-drawer__item-btn drawer__item-btn js-languagepicker-item-btn{{#any _isSelected _isDisabled}} is-disabled{{/any}}" data-language="{{_language}}"{{#any _isSelected
Makes sense

2022-05-25 14:26 UTC, kirsty-hames requested changes
+1 if suggestion is applied https://github.com/adaptlearning/adapt-contrib-languagePicker/pull/65#discussion_r872522510

2022-06-21 13:55 UTC, chris-steele approved these changes

2022-06-21 14:04 UTC, merged